apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo-app
spec:
  containers:
  - name: webserver
    image: demo-flask-app:0.1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
